[package]
name = "bucky"
version = "0.1.0"
authors = ["Frederick Lahde <fredlahde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.44"